version: "1.0"

services:
   flask_app:
      container_name: flask_app
      image: dockerhub-flask_live_app:1.0.0
      ports: 
        - "5000:5000"
      depends_on:
        - flask_db
   flask_db:
      container_name: flask_db
      image: keinos/sqlite3:latest

volumes:
   sqlitedata: {}
   
